//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualitestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTable
    {
        public int Id { get; set; }
        public string MovieName { get; set; }
        public string MovieBody { get; set; }
        public string Year { get; set; }
        public string Country { get; set; }
        public string Category { get; set; }
        public string Quality { get; set; }
        public string Length { get; set; }
        public string MoviePicture { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
